#!/usr/bin/env bash

# Run the installer
"$TRAVIS_BUILD_DIR/texlive/installer"

# Standard post install step.
# MEMO: /tmp/texlive is defined as root in the profile file.
export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
